//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int accountId { get; set; }
        public string pass { get; set; }
        public string app { get; set; }
        public string names { get; set; }
        public string llave_de_recuperacion { get; set; }
    }
}
